version: 0.0

os: linux
files:
  - source: .
    destination: /home/ec2-user/
hooks:
  BeforeInstall:
    - location: ./scripts/reset_env.sh
      timeout: 300
      runas: root
  Install:
    - location: ./scripts/set_env.sh
      runas: root
  ApplicationStart:
    - location: ./scripts/start_app.sh
      runas: root
