version: 0.0

os: linux
files:
  - source: .
    destination: /home/ec2-user/
hooks:
  Install:
    - location: ./scripts/load_image
      runas: root
  ApplicationStart:
    - location: ./scripts/run_container
      runas: root