name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Copy Secret
      env:
        CONFIG_SECRET: ${{ secrets.CONFIGS }}
        CONFIG_SECRET_DIR: ./
        CONFIG_SECRET_FILE_NAME: config.ini
      run: echo $COFNIG_SECRET | base64 --decode > $CONFIG_SECRET_DIR/$CONFIG_SECRET_FILE_NAME
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME}}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Docker image Build and Push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKER_HUB_USERNAME }}/money_gone:latest