name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Copy Secret
        env:
          CONFIG_SECRET: ${{ secrets.CONFIGS }}
          CONFIG_SECRET_DIR: data/
          CONFIG_SECRET_FILE_NAME: config.ini
        run: echo $COFNIG_SECRET | base64 --decode > $CONFIG_SECRET_DIR/$CONFIG_SECRET_FILE_NAME

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME}}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Data image Build and Push
        uses: docker/build-push-action@v2
        with:
          context: data/
          file: data/Dockerfile.data
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/money_gone_data:latest

      - name: WAS image Build and Push
        uses: docker/build-push-action@v2
        with:
          context: was/
          file: was/Dockerfile.was
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/money_gone_was:latest

  continuous-deployment:
    runs-on: ubuntu-latest
    needs: [continuous-integration]

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create CodeDeploy Deployment
        id: deploy
        run: |
          aws deploy create-deployment \
           --application-name money-gone-was-cd \
          --deployment-group-name Money-Gone-CDG \
          --deployment-config-name CodeDeployDefault.OneAtATime \
          --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
